### ISSUE TITLE
Problems using the CLI

### ISSUE THREAD

**Issue by Apollo3zehn** [Zeugwerk/vscode-plaincat#1]
Hi, first of all, thank you for providing this tool :-)

Two problems occured trying to use the CLI:

 - First, I had to set the `<JavaExec>PATH</JavaExec>` to a real java executable path
 - And it seems that the `typeof(EncodeOptions)` is missing in `Program.cs` because the CLI complains that the verb `encode` is not known

Edit: 
- Please consider using forward slashes instead of backslashes in `FileInterface.cs` so that it works on all major operating systems (Windows, Linux, Mac)

**Comment by beslst** [comment]
Thanks for trying out this little project :)

Without specifying `<JavaExec>PATH</JavaExec> ` and having the Java bin in my PATH, AntlrTasks had some problems for me picking up the correct path. I‘ll see if it works with newer release and probably there is a better solution

The other points, sure we‘ll fix them, we are also happy about PR especially for the vscode plugin part :)

**Comment by beslst** [comment]
Solved with
- 7a4b55919670532e5ba174bf8b63e265442cb6d1
- 8fde4cb14151ac73b163c46a28dc3eccb986f1b6

**Comment by Apollo3zehn** [comment]
Thanks, very nice :-)
